/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Default: typeof import('./src/layouts/default/default.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/layouts/default/sideBar.vue')['default']
  }
}
